# Generated by Django 4.2.20 on 2025-04-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='comment',
        ),
    ]
