# Generated by Django 4.2.20 on 2025-04-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_deposit_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='date',
        ),
    ]
