# Generated by Django 4.2.20 on 2025-04-27 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposited_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 7, 7, 53, 208660, tzinfo=datetime.timezone.utc)),
        ),
    ]
