# Generated by Django 4.2.20 on 2025-04-27 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deposit_deposited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
