# Generated by Django 4.2.20 on 2025-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_deposit_deposited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtrade',
            name='final_order',
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='close_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='completedtrade',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
