# Generated by Django 4.2.20 on 2025-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_completedtrade_final_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtrade',
            name='close_date',
            field=models.DateField(),
        ),
    ]
