# Generated by Django 4.2.20 on 2025-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_completedtrade_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtrade',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
