# Generated by Django 4.2.20 on 2025-04-27 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_completedtrade_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtrade',
            name='close_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
