# Generated by Django 4.2.20 on 2025-04-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_completedtrade_close_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtrade',
            name='close_date',
        ),
    ]
